@BookTracker.Api_HostAddress = http://localhost:5283 
###@BookTracker.Api_HostAddress = http://localhost:5000 ?

### Get Books
GET {{BookTracker.Api_HostAddress}}/books
Accept: application/json

### Get Book by Id
GET {{BookTracker.Api_HostAddress}}/books/1
###
GET {{BookTracker.Api_HostAddress}}/books/9999
### Create Book
POST {{BookTracker.Api_HostAddress}}/books
Content-Type: application/json

{
  "title": "Dune",
  "author": "Frank Herbert",
  "year": 1965
}

### Delete Book
DELETE {{BookTracker.Api_HostAddress}}/books/1
###
DELETE {{BookTracker.Api_HostAddress}}/books/9999

###
### Update Book
PUT {{BookTracker.Api_HostAddress}}/books/1
Content-Type: application/json

{
  "title": "Changes",
  "author": "David Bowie",
  "year": 1971
}
###
PUT {{BookTracker.Api_HostAddress}}/books/9999
Content-Type: application/json

{
  "title": "Unknown Book",
  "author": "Unknown Author",
  "year": 2000
}

### Get Books Page 1
GET {{BookTracker.Api_HostAddress}}/books?page=1&pageSize=10

### Get Books Page 2
GET {{BookTracker.Api_HostAddress}}/books?page=2&pageSize=10

### Search Books
GET {{BookTracker.Api_HostAddress}}/books?search=octopus

### Search Books With Paging
GET {{BookTracker.Api_HostAddress}}/books?search=octopus&page=1&pageSize=5